# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
