# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20170211_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
