# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20170211_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
