# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hidden',
            field=models.CharField(default='qwe', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
